function seforVerdade(valor){
    if(valor){
        console.log('É verdade... ' + valor)
    }
}
seforVerdade()
seforVerdade(null)
seforVerdade(undefined)
seforVerdade(NaN)
seforVerdade('')
seforVerdade(0)
seforVerdade(-1)
seforVerdade(' ')
seforVerdade('?')
seforVerdade([])
seforVerdade([1, 2])
seforVerdade({})
seforVerdade({ nome: 'maicon'})
seforVerdade(function(){})
seforVerdade(()=>{})
seforVerdade(123)
seforVerdade('texto')
seforVerdade(true)
seforVerdade(false)
seforVerdade(new Date())
seforVerdade(Infinity)
seforVerdade(-Infinity)
seforVerdade(3.14)
seforVerdade('0')
seforVerdade('false')